### ISSUE TITLE
EPIC: Erkennung von Regelverstößen

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/LibCommon#12]
Während der Durchführung des Spiels muss der Server die Aktionen jedes Clients
auf Regelkonformität prüfen. Ungültige Aktionen werden vom Server abgelehnt.

**Comment by authaldo** [comment]
Fällt das nicht in den Bereich von LibCommon?

**Comment by ottojo** [comment]
Ja tut es. here we go.

**Comment by csacro** [comment]
Description:
Jede Nachricht, die ein Client sendet bzw. der Server empfängt muss validiert werden. Da Client und Server unterschiedliche Model haben und kein Model in LibCommon implementiert ist, müssen z.B. Validierung von clientId, sessionId ("gehört diese Nachricht zu mir") oder "darf diese Nachricht jetzt gesendet werden" jeweils im Client oder Server implementiert werden falls notwendig.

FYI: Ich habe in LibClient bei der [initialen Struktur](https://github.com/SoPra-Team-17/LibClient/pull/9) bereits "ausversehen" Validierung auf RoleEnum für jede Nachricht implementiert und in das TODO ein paar Stichpunkte, was man sonst noch validieren kann/muss. (Hatte nicht daran gedacht, dass das ja hier gemacht wird).
