### ISSUE TITLE
Operation validation and execution fix

### ISSUE THREAD

**Issue by csacro** [SoPra-Team-17/LibCommon#132]
Wie werden eigentlich Operationen vom Typ 'SPY_ACTION' validiert und ausgeführt? Diese haben ja aktuell keine spezielle Operationsklasse.
Des weiteren habe keine spezielle Operationsklasse Operationen vom Typ 'JANITOR_ACTION', 'CAT_ACTION'  und 'RETIRE'. Für die letzten drei braucht man eigentlich nur eine execute-Methode, da janitor und cat vom Server bewegt werden und retire immer valide ist, wenn der Spieler am Zug ist.

**Comment by ottojo** [comment]
Ich glaube das ist related zu #134 und der Diskussion heute mittag... Ich habe mal über die Operation-Datenstruktur nachgedacht und bin hier bei rausgekommen:
![Screenshot from 2020-04-29 17-18-37](https://user-images.githubusercontent.com/7536298/80613535-b440b880-8a3d-11ea-9715-402a4f467156.png)

Also explizite Klassen für alle Operation-typen, die CharacterOperation nur als helper (fügt characterId hinzu).
Und an allen stellen wo zur compiletime nicht bekannt ist, was für eine Operation man hat, kann man `std::shared_ptr<BaseOperation>` verwenden. Wie das mit JSON funktioniert weiß ich noch nicht, vielleicht baut man sich ein Methode die auch einen ptr auf BaseOperation zurückgibt.

**Comment by ottojo** [comment]
Für validation und execution dann eine public methode die auch ptr auf BaseOperation bekommt und dann switch/case macht

**Comment by csacro** [comment]
RetireAction müsste aber auch eine CharacterOperation sein

**Comment by csacro** [comment]
Hast du da schon was implementiert (sieht verdächtig nach Doxygen aus) ?

**Comment by ottojo** [comment]
Ja #137
