### ISSUE TITLE
Gadget benötigt Range und Probability

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/LibCommon#133]
Die momentane Implementierung von Gadget enthält weder die Range noch die Probability. Beide werden aber für die Validierung / Execution benötigt. Entweder zugängig machen der MatchConfig im State oder einlesen der Werte ins Gadget.

**Comment by ottojo** [comment]
Relates to #129

**Comment by authaldo** [comment]
Vorschlag: nach dem Merge von #137 nimmt man die MatchConfig als const reference in den obersten Aufruf zu validate ([hier](https://github.com/SoPra-Team-17/LibCommon/blob/355593759267a4ed9acb63541e35815f0a263fe6/src/datatypes/validation/ActionValidator.cpp#L9)) auf und verteilt sie von da aus an die einzelnen Gadget validation Methoden
