### ISSUE TITLE
Property Honey Trap

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/LibCommon#201]
Wurde bislang nicht beachtet

**Comment by Marco5de** [comment]
Betroffene Gadgets
- [ ] Cocktail
- [ ] Klingen Hut
- [ ] Laser Compact ein Angriff?
- [ ] Gas Gloss
- [ ] Wiretap ein Angriff?

**Comment by csacro** [comment]
Lösungs-Idee
* Wahrscheinlichkeitsprobe
* wenn erfolgreich (hierfür Methode, die State und ursprüngliche Operation nimmt und neue Operation zurückgibt)  
CharacterSet durchgehen und als target der Aktion setzen (Ausführer und Honey Trapper auslassen)  
jede Aktion mit validate prüfen und so liste valider targets erstellen
zufälliges target aus Liste wählen (falls liste leer ursprüngliches target)

**Comment by csacro** [comment]
Aktionen die gegen eine Person gehen, also target ein Feld mit einem Charakter drauf ist:
- [x] Cocktail, aber nur verschütten (TODO)
- [x] Poison Pills, aber nur wenn man den Cocktail hält
- [x] Bowler Blade
- [x] Gas Gloss
- [x] Laser Compact
- [x] Mode Die, aber nur wenn auf Person geworfen wird
- [x] Rocket Pen, aber nur wenn auf Person geschossen
- [ ] Nugget (würde ich nicht machen)
- [ ] Mirror of Wilderness (würde ich nicht machen)
- [ ] Wiretrap with Earplugs  (würde ich nicht machen)
- [ ] Hair Dryer (würde ich nicht machen)

**Comment by authaldo** [comment]
Ich finde die bisher umgesetzte Auswahl gut. Bei den restlichen fehlt mir für einen "Angriff" die negative Wirkung :+1:

**Comment by csacro** [comment]
Implemetiert, aber noch nicht getestet
