### ISSUE TITLE
Eliminate use of unnecessary calls to general action validation function

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/LibCommon#268]
Performance could probably be gained by calling the proper (specialized) action validation instead of the general function when type is known. Relevant in case of action generation.

TODO:
- [x] Measure performance
If relevant:
- [x] Make validations public
- [x] Change generation methods

**Comment by ottojo** [comment]
Benchmarken hat ergeben:
```
-----------------------------------------------------------
Benchmark                 Time             CPU   Iterations
-----------------------------------------------------------
GenericValidate        2177 ns         2175 ns       280573
SpecificValidate       2088 ns         2087 ns       490532
GenericValidate        2474 ns         2474 ns       382992
SpecificValidate       1437 ns         1437 ns       536517
```
(jeweils pro benchmark-iteration 1x `generateMovementAction` mit 2 validen movements)

**Comment by authaldo** [comment]
Ich finde die Auswirkungen sind signifikant und ich sehe auch nicht wirklich ein Problem dabei die Funktionen public zu machen

**Comment by csacro** [comment]
waiting for Sprint2 to be finished
