### ISSUE TITLE
Generate should return list and not vector

### ISSUE THREAD

**Issue by csacro** [SoPra-Team-17/LibCommon#274]

**Comment by csacro** [comment]
waiting for Sprint2 to be finished

**Comment by authaldo** [comment]
Von der Nutzung mit dem häufigen Einfügen her wäre ich davon ausgegangen, dass eine Liste besser performed als ein Vektor, allerdings wurde das ganze [hier](https://baptiste-wicht.com/posts/2012/11/cpp-benchmark-vector-vs-list.html) bereits ausführlich gebenchmarked. Dabei war das Ergebnis gerade umgekehrt, bei kleinen Datenmengen (wie sie bei uns vorliegen), ist der Vektor durch die Caches sogar besser.
Von daher schließe ich dieses Issue mal.
