### ISSUE TITLE
new gadget "Anti-Seuchen-Schnabelmaske"

### ISSUE THREAD

**Issue by csacro** [SoPra-Team-17/LibCommon#276]
> Anti-Seuchen-Schnabelmaske: Eine gesundheitsförderliche Maske in venezianischem Design, die den Träger vor allerlei Krankheiten bewahrt. Wenn ein Charakter die Schnabelmaske im Inventar hat, bekommt er immer zu Beginn seines Zuges 10 HP zugeschrieben (natürlich nur, bis er den Maximalwert von 100 HP erreicht hat).

Muss an folgenden Stellen beachtet werden:
- [x] GadgetEnum
- [ ] RoundUtils bzw. bei Zug
- [x] validate, execute, generate (nur im switch case, keine Implementierung der Aktion)

**Comment by authaldo** [comment]
Die Anwendung des Gadgets beim Zug würde ich direkt im Server machen

**Comment by csacro** [comment]
Hätte das zu den RoundUtils, weil dann könnte die KI das auch nutzen, falls jemand eine rundenübergreifende Strategie implementieren will
edit: Im Gegensatz zu AP/BP Initialisierung macht es einen Unterschied, ob die HP zu Begin der Runde oder erst zum Zug hinzugefügt werden.
