### ISSUE TITLE
Replay messages

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/LibCommon#44]
Der member `Replay::messages` ist momentan `std::vector<MessageContainer>`, was es nicht erlaubt da tatsächlich Instanzen von speziellen Messages zu speichern ohne alle Member der Child-Klassen wegzuschmeißen. Möglicher Fix: ``std::vector<std::variant<Messages...>>`.

Wäre es auch ein Fix, da `std::shared_ptr<MessageContainer>` zu speichern oder wird da auch data discarden?

**Comment by csacro** [comment]
optional feature that currently will not be implemented
