### ISSUE TITLE
Install target

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/LibCommon#7]
Install target testen + fixen

**Comment by ottojo** [comment]
https://github.com/SoPra-Team-17/LibCommon/pull/2#discussion_r402582473

**Comment by csacro** [comment]
mit #51 kann man die library jetzt ja gar nicht mehr installieren, sondern nur noch als Submodule einbinden oder?

**Comment by ottojo** [comment]
Genau, wir hatten uns mal entschieden das immer so zu machen IIRC
