### ISSUE TITLE
UUID Klasse/Lib

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/LibCommon#8]
+ JSON

Für die UUID Klasse könnte man sich das [hier](https://github.com/mariusbancila/stduuid) anschauen.

_Originally posted by @authaldo in https://github.com/SoPra-Team-17/LibCommon/pull/2#issuecomment-608048274_

**Comment by ottojo** [comment]
Ich update das hier mal mit meinen Erkenntnissen:
* Unter Linux gibts [libuuid](https://linux.die.net/man/3/libuuid)(c), ist sehr kompakt und ein wrapper ist easy (habe mal zum spaß einen geschrieben, 60LOC)
* [stduuid](https://github.com/mariusbancila/stduuid) hat kein cmake install target
* [crossguid](https://github.com/graeme-hill/crossguid) ist ein libuuid wrapper, + wrapper für entsprechende Windows/Mac funktionen. Nicht besonders schön, wenn die Win/Mac funktionalität nicht interessiert würde ich da lieber selber einen libuuid wrapper basteln.
* [sole](https://github.com/r-lyeh-archived/sole) ist weird, und benutzt zu viel präprozessor

**Comment by ottojo** [comment]
@authaldo Schau dir die doch auch mal an und füg ggf Alternativen hinzu

**Comment by authaldo** [comment]
Ich sehe das ähnlich wie du:
 * sole ist wirklich komisch
 * crossguid ist nicht wirklich notwendig, da das Lastenheft lediglich fordert, dass der Client auf einer Plattform läuft (bei uns dann wohl Linux)
 * libuuid finde ich nicht schlecht, auch wenn man den Wrapper selber schreiben müsste
 * bei stduuid finde ich den gsl Teil etwas komisch, allein dass die Files keine .h oder .hpp Endung haben. Aber da es Header-only ist dürfte die Installation mittels CMake ja kein so großes Problem darstellen

Push mal deinen Wrapper, da wir keine Plattformunabhängigkeit gewährleisten müssen, sollte das die einfachste Variante sein
